net: oplus_sla: Fix ip_route_me_harder() call with missing sock argument
The function ip_route_me_harder() requires 4 arguments, but the call in
oplus_sla.c only provided 3, causing a compilation error:

  ../net/oplus_sla/oplus_sla.c:2190:54: error: too few arguments to function call
  expected 4, have 3